### ISSUE TITLE
str(ULID()) infinite recursion

### ISSUE THREAD

**Issue by kcburge** [tsmanikandan/py-ulid#5]
Wanting to try this library, I went in to iPython (Python 3.7) and typed:

from ulid import ULID
ULID()

Output:

~/local/py3env/lib/python3.7/site-packages/ulid/ulid.py in __repr__(self)
     45
     46     def __repr__(self):
---> 47         return "%s(%r)" % (self.__class__.__name__, **str(self)**)
     48
     49     # Function to generate the ulid without monotonicity or ms time handling

**RecursionError: maximum recursion depth exceeded while getting the str of an object**

Not a critical bug, but thought it worth mentioning, as every other ulid library I tried had some kind of problem and I was about to abandon this one too, but then tried the instructions according to the documentation.

**Comment by tsmanikandan** [comment]
Hi @kcburge ,

Thank you for checking out my library and logging this Issue! I highly appreciate it.
The error stems from an earlier iteration of the program where I had a custom __repr__ function, which is not necessary for the current implementation.
I have now fixed the bug.
